name: Action hello # name my workflow

on:
  push:
    branches:
      - master

jobs:
  build: #job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run script
        run: python hello.py
